"""The real backend, and the switch that decides whether it is even loaded.

The front end suite runs against ``web/dummy_api.py``; these are the tests for
``backend/``, the swarm that answers when the switch is off.  Nothing here
sends a prompt: the Gemini client is a :class:`~unittest.mock.MagicMock`, so
the agents run their real logic and every model call is a stub that returns
canned text.  That is affordable where a real playtest is not, and it is the
only way to exercise the whole run - the rules conversation, codegen, the game
loop, the analyses and the review - in a second.

The last section is the connection itself: the front end's own flow, driven
through :func:`web.pipeline.turn` against the real backend, so the seam the
switch sits on is asserted rather than assumed.
"""

from __future__ import annotations

import inspect
import json
import os
import sys
from typing import Any
from unittest.mock import MagicMock

import pytest

import api_errors
import backend.api as backend_api
import backend.swarm as swarm
import web.app as app
import web.dummy_api as dummy_api
import web.pipeline as pipeline
import web.ui as ui

WEB_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

#: The engine the coding step is stubbed with: a whole game that ends on the
#: first move, so a run reaches the review without a long playtest.
ENGINE_SOURCE = '''"""A one-move game, generated by the Rules agent in the test suite."""


def initial_game_state(player_count):
    return {"turn": 0, "moves": 0, "players": player_count}


def list_valid_moves(game_state, player_id):
    return [{"action": "pass"}]


def execution_function(game_state, move, player_id):
    return {
        "turn": game_state["turn"] + 1,
        "moves": game_state["moves"] + 1,
        "players": game_state["players"],
    }


def eval_function(game_state):
    return 0 if game_state["moves"] >= 1 else None


def translation_function(x1, x2, p):
    return x1


def get_random_valid_move(game_state, player_id):
    return {"action": "pass"}
'''

RULES = (
    "Skirmish, restated from the designer's description. Two players pass in "
    "turn until someone has passed once.\n"
    "[GAME_NAME: Skirmish]\n[PLAYER_COUNT: 2]"
)

#: The same game with nothing in it that can be won, for the draw at the turn
#: limit.
ENDLESS_SOURCE = ENGINE_SOURCE.replace(
    'return 0 if game_state["moves"] >= 1 else None', "return None"
)

PROMPT = "a two player game where passing wins"

#: What the switch says before any fixture has touched it.  The suite turns the
#: switch on for every test, so the shipped default has to be read at import.
SWITCH_DEFAULT = app.USE_DUMMY_API

FINDINGS = [
    {
        "title": "Opening move is solved",
        "detail": "The centre was taken on turn 1 in every game.",
        "severity": "medium",
    },
    {
        "title": "Dead turns",
        "detail": "Two attempts were rejected as illegal.",
        "severity": "low",
    },
]

REVIEW = "Here is what the playtests say about Skirmish. Two things stand out."


# ---------------------------------------------------------------------------
# Doubles: a client that cannot spend anything
# ---------------------------------------------------------------------------


@pytest.fixture(autouse=True)
def no_live_gemini(monkeypatch) -> None:
    """Belt and braces: no test in this file may reach a real Gemini.

    The ``gemini`` fixture below covers every path through the swarm, because
    ``get_client`` is the only one there is.  This is the backstop for the rest:
    if some future test forgets the fixture, building an actual client - and
    with it spending actual money - fails the run instead of quietly happening.
    """

    monkeypatch.setattr(
        swarm.genai,
        "Client",
        MagicMock(side_effect=AssertionError("a test tried to build a real client")),
    )


@pytest.fixture
def gemini(monkeypatch) -> MagicMock:
    """The Gemini client, made of mocks.

    ``swarm.get_client`` is the only way the swarm reaches a model, so
    replacing it is enough to keep every test here off the network and out of
    the wallet.
    """

    double = MagicMock()
    monkeypatch.setattr(swarm, "get_client", lambda: double)
    return double


def _reply(value: Any) -> MagicMock:
    """A model reply: text back, or an exception standing in for a dead swarm."""

    if isinstance(value, BaseException) or (
        inspect.isclass(value) and issubclass(value, BaseException)
    ):
        return MagicMock(side_effect=value)
    return MagicMock(text=value)


def says(gemini: MagicMock, *replies: Any) -> MagicMock:
    """The Rules agent's chat, saying these things in this order."""

    chat = MagicMock()
    chat.send_message.side_effect = [_reply(reply) for reply in replies]
    gemini.chats.create.return_value = chat
    return chat


def generates(gemini: MagicMock, *replies: Any) -> None:
    """One-shot completions, in this order."""

    gemini.models.generate_content.side_effect = [_reply(reply) for reply in replies]


@pytest.fixture(autouse=True)
def clean_backend():
    """Conversations do not outlive a test."""

    backend_api.reset()
    yield
    backend_api.reset()


# ---------------------------------------------------------------------------
# The switch
# ---------------------------------------------------------------------------


def test_the_switch_is_off_for_a_normal_run(monkeypatch):
    # This suite turns the switch on for itself; what is being asserted here is
    # the default it was shipped with, read before any fixture touched it.
    assert SWITCH_DEFAULT is False
    monkeypatch.setattr(app, "USE_DUMMY_API", SWITCH_DEFAULT)
    assert app.active_api() is backend_api
    assert pipeline.resolve_api() is backend_api


def test_the_switch_is_on_while_the_front_end_is_tested(monkeypatch):
    monkeypatch.setattr(app, "USE_DUMMY_API", True)
    assert app.active_api() is dummy_api
    assert pipeline.resolve_api() is dummy_api


def test_the_two_apis_are_interchangeable():
    """Whatever the switch selects, the pipeline calls it the same way.

    The pipeline is written against this list and nothing else, so a difference
    in a name, an argument or its default breaks the turn the moment the switch
    is flipped.
    """

    for name in (
        "interpret_rules",
        "generate_code",
        "deploy_instances",
        "play_sample_game",
        "collect_analyses",
        "design_feedback",
    ):
        real = inspect.signature(getattr(backend_api, name))
        stand_in = inspect.signature(getattr(dummy_api, name))
        assert list(real.parameters) == list(stand_in.parameters), name


def test_the_switch_is_not_visible_to_the_user():
    """Nothing on the page can see it, so nobody can reach for it."""

    for path in ("templates/index.html", "templates/feed.html", "static/js/app.js"):
        with open(os.path.join(WEB_DIR, "web", path), encoding="utf-8") as handle:
            page = handle.read()
        assert "USE_DUMMY_API" not in page, path
        assert "dummy" not in page.lower(), path


# ---------------------------------------------------------------------------
# The rules conversation, held open
# ---------------------------------------------------------------------------


def test_the_rules_agent_is_given_the_design_and_its_system_instruction(gemini):
    chat = says(gemini, RULES)
    reading = backend_api.interpret_rules("a game about deep space", (), "run-1")

    chat.send_message.assert_called_once()
    sent = chat.send_message.call_args.args[0]
    assert "deep space" in sent
    assert swarm.RULES_SYSTEM_INSTRUCTION == gemini.chats.create.call_args.kwargs["config"].system_instruction
    assert reading.needs_clarification is False


def test_a_reply_without_a_player_count_is_a_question(gemini):
    says(gemini, "How many players are there, and what is a legal turn?")
    reading = backend_api.interpret_rules("something fun, you decide", (), "run-1")

    assert reading.needs_clarification is True
    assert reading.question == "How many players are there, and what is a legal turn?"
    assert reading.rules == ""


def test_the_same_run_answers_in_the_same_conversation(gemini):
    chat = says(gemini, "How many players?", "And what is a turn?", RULES)
    backend_api.interpret_rules("something fun, you decide", (), "run-1")
    reading = backend_api.interpret_rules(
        "something fun, you decide", ("Two players.", "A turn is one counter."), "run-1"
    )

    # One chat, asked once and then told the answers: the agent keeps everything
    # it was told the first time.
    gemini.chats.create.assert_called_once()
    assert chat.send_message.call_count == 3
    assert chat.send_message.call_args_list[1].args == ("Two players.",)
    assert reading.needs_clarification is False
    assert reading.rules == RULES
    assert reading.game_name == "Skirmish"
    assert reading.player_count == 2


def test_the_conversation_keeps_its_own_place_in_the_answer_list(gemini):
    """A caller that sends the whole answer list does not repeat old answers."""

    chat = says(gemini, "How many players?", "And how do you win?", RULES)
    answers = ("Two players.", "Three in a row.")
    backend_api.interpret_rules("vague", answers[:1], "run-1")
    backend_api.interpret_rules("vague", answers, "run-1")

    assert chat.send_message.call_count == 3
    assert chat.send_message.call_args_list[-1].args == ("Three in a row.",)


def test_a_new_run_starts_a_new_conversation(gemini):
    chat = says(gemini, "How many players?", RULES)
    backend_api.interpret_rules("a game about dice", (), "run-1")
    reading = backend_api.interpret_rules(
        "a game about dice, now with cards", (), "run-2"
    )

    assert gemini.chats.create.call_count == 2
    # A new run is a new conversation, and it is sent the whole definition, the
    # part that was appended included.
    assert "a game about dice, now with cards" in chat.send_message.call_args_list[-1].args[0]
    assert backend_api._CONVERSATIONS["run-1"] is not backend_api._CONVERSATIONS["run-2"]
    assert reading.player_count == 2


def test_a_run_without_a_key_still_works(gemini):
    """No run means no conversation to keep, so nothing is held open."""

    says(gemini, RULES)
    backend_api.interpret_rules("a game of dice")
    assert backend_api._CONVERSATIONS == {}


def test_conversations_do_not_pile_up(gemini, monkeypatch):
    says(gemini, *[RULES] * 5)
    monkeypatch.setattr(backend_api, "MAX_LIVE_CONVERSATIONS", 3)

    for run in range(1, 6):
        backend_api.interpret_rules("a game of dice", (), f"run-{run}")

    assert list(backend_api._CONVERSATIONS) == ["run-3", "run-4", "run-5"]


# ---------------------------------------------------------------------------
# Coding
# ---------------------------------------------------------------------------


def test_the_code_is_the_python_block_and_nothing_else(gemini):
    generates(gemini, f"Here you go:\n```python\n{ENGINE_SOURCE}```\nHope that helps.")
    code = backend_api.generate_code(RULES)

    assert code == ENGINE_SOURCE
    assert "```" not in code
    # Strict code, so the same rules give the same engine.
    assert gemini.models.generate_content.call_args.kwargs["config"].temperature == 0.0


def test_a_reply_with_no_code_block_is_a_loss_of_service(gemini):
    generates(gemini, "I am afraid I could not write that.")
    with pytest.raises(api_errors.BackendUnavailable):
        backend_api.generate_code(RULES)


def test_the_engine_is_loaded_in_memory(gemini, tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    deployment = backend_api.deploy_instances(RULES, ENGINE_SOURCE)

    assert deployment.engine.initial_game_state(2)["players"] == 2
    # Nothing was written down, and nothing was left on the import path.
    assert list(tmp_path.iterdir()) == []
    assert "generated_engine" not in sys.modules


def test_an_engine_that_will_not_load_is_a_loss_of_service():
    with pytest.raises(api_errors.BackendUnavailable, match="would not load"):
        swarm.load_engine("def initial_game_state(:\n")


# ---------------------------------------------------------------------------
# Deploying: the player agents
# ---------------------------------------------------------------------------


def test_deploying_is_one_player_agent_per_player(gemini):
    deployment = backend_api.deploy_instances(
        RULES.replace("[PLAYER_COUNT: 2]", "[PLAYER_COUNT: 4]"), ENGINE_SOURCE
    )

    assert deployment.instances == 4
    assert [player.player_id for player in deployment.players] == [0, 1, 2, 3]
    assert all(isinstance(p, swarm.PlayerAgent) for p in deployment.players)
    assert deployment.urls == [
        f"https://sandbox.local/game/{index}" for index in range(1, 5)
    ]


def test_a_deployment_with_no_player_count_gets_two_players(gemini):
    deployment = backend_api.deploy_instances("Skirmish, two players, no tags here", ENGINE_SOURCE)
    assert deployment.instances == 2


# ---------------------------------------------------------------------------
# Playing
# ---------------------------------------------------------------------------


def play_one(gemini) -> list[dict]:
    """A deployed game, played, with the coding step stubbed out."""

    generates(
        gemini,
        json.dumps({"move": {"action": "pass"}, "explanation": "Nothing beats a pass."}),
    )
    deployment = backend_api.deploy_instances(RULES, ENGINE_SOURCE)
    return backend_api.play_sample_game(RULES, deployment)


def test_the_sample_game_is_the_swarm_reasoning_through_the_game(gemini):
    sample = play_one(gemini)

    assert sample[-1]["outcome"] == "Player 1 wins on turn 1 of 2."
    assert sample[0]["turn"] == 1
    # The engine counts players from 0; a reader counts from 1.
    assert sample[0]["player"] == 1
    assert sample[0]["move"] == {"action": "pass"}
    assert sample[0]["explanation"] == "Nothing beats a pass."
    assert "illegal" not in sample[0]


def test_an_illegal_move_is_kept_as_a_misfire(gemini, monkeypatch):
    monkeypatch.setattr(swarm, "MAX_RETRIES", 2)
    generates(
        gemini,
        json.dumps({"move": {"action": "cheat"}, "explanation": "Winning."}),
        json.dumps({"move": {"action": "cheat"}, "explanation": "Still winning."}),
    )
    deployment = backend_api.deploy_instances(RULES, ENGINE_SOURCE)
    sample = backend_api.play_sample_game(RULES, deployment)

    rejected = [record for record in sample if record.get("illegal")]
    assert len(rejected) == 2
    assert rejected[0]["move"] == {"action": "cheat"}
    # Then the fallback move the engine offered, and the reason it was forced.
    assert sample[-1]["move"] == {"action": "pass"}
    assert sample[-1]["explanation"] == "Forced random move due to invalid attempts."


def test_an_unreadable_reply_is_retried_then_forced(gemini):
    generates(
        gemini,
        "I think I will go with the corner.",
        json.dumps({"move": {"action": "pass"}, "explanation": "A pass it is."}),
    )
    deployment = backend_api.deploy_instances(RULES, ENGINE_SOURCE)
    sample = backend_api.play_sample_game(RULES, deployment)

    assert sample[0]["illegal"] is True
    assert "Unreadable reply" in sample[0]["explanation"]
    assert sample[1]["move"] == {"action": "pass"}


def test_a_game_that_never_ends_is_a_draw(gemini, monkeypatch):
    monkeypatch.setattr(swarm, "MAX_TURNS", 1)
    generates(
        gemini,
        json.dumps({"move": {"action": "pass"}, "explanation": "Passing."}),
        json.dumps({"move": {"action": "pass"}, "explanation": "Passing."}),
    )
    deployment = backend_api.deploy_instances(RULES, ENDLESS_SOURCE)
    sample = backend_api.play_sample_game(RULES, deployment)

    assert len(sample) == 2  # one turn, one action per player
    assert "draw" in sample[-1]["outcome"]


def test_losing_service_while_playing_is_a_loss_of_service(gemini):
    generates(gemini, RuntimeError("the swarm is down"))
    deployment = backend_api.deploy_instances(RULES, ENGINE_SOURCE)
    with pytest.raises(api_errors.BackendUnavailable):
        backend_api.play_sample_game(RULES, deployment)


# ---------------------------------------------------------------------------
# The design agent
# ---------------------------------------------------------------------------


def test_the_playtests_become_findings(gemini):
    generates(gemini, json.dumps(FINDINGS))
    sample = [
        {
            "turn": 1,
            "player": 1,
            "move": {"action": "pass"},
            "explanation": "Nothing beats a pass.",
            "illegal": True,
        }
    ]
    findings = backend_api.collect_analyses(RULES, sample)

    assert [finding["title"] for finding in findings] == [
        "Opening move is solved",
        "Dead turns",
    ]
    # The misfire survived the trip, because dead turns are what it looks for.
    sent = gemini.models.generate_content.call_args.kwargs["contents"]
    assert '"type": "misfire"' in sent


def test_findings_the_design_agent_leaves_half_written_are_filled_in(gemini):
    generates(gemini, "```json\n" + json.dumps([{"detail": "A player never moved."}]) + "\n```")
    findings = backend_api.collect_analyses(RULES, [])

    assert findings == [
        {"title": "Untitled finding", "detail": "A player never moved.", "severity": "medium"}
    ]


def test_a_reply_that_is_not_a_list_of_findings_is_a_loss_of_service(gemini):
    generates(gemini, "I could not do it.")
    with pytest.raises(api_errors.BackendUnavailable):
        backend_api.collect_analyses(RULES, [])


def test_the_review_is_the_long_answer(gemini):
    generates(gemini, REVIEW)
    answer = backend_api.design_feedback("a game about deep space", RULES, FINDINGS)

    assert answer == REVIEW
    sent = gemini.models.generate_content.call_args.kwargs["contents"]
    assert "deep space" in sent
    assert "Dead turns" in sent


# ---------------------------------------------------------------------------
# The helpers the swarm is built on
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    "value, listed",
    [
        ([40, 200, 1], True),
        ([0.0, 1.0, 0.1], True),
        ([-10, 10, 2], True),
        ([True, 10, 1], False),  # a bool is not a number here
        ([0, 10, 0], False),  # a step of zero never lands
        ([1, 10], False),
        ([1, 10, 2, 5], False),
        ("not a list", False),
        ([1, "10", 2], False),
    ],
)
def test_a_range_spec_is_three_numbers_with_a_step(value, listed):
    assert swarm._is_range_spec(value) is listed


@pytest.mark.parametrize(
    "chosen, spec, on_lattice",
    [
        (40, [40, 200, 1], True),  # the minimum is inclusive
        (199, [40, 200, 1], True),
        (200, [40, 200, 1], False),  # the maximum is not
        (39, [40, 200, 1], False),
        (41, [40, 200, 2], False),  # off the lattice
        (True, [40, 200, 1], False),
        ("40", [40, 200, 1], False),
        (0.4, [0.0, 1.0, 0.2], True),
    ],
)
def test_a_chosen_number_has_to_land_on_the_lattice(chosen, spec, on_lattice):
    assert swarm._number_in_range(chosen, spec) is on_lattice


def test_a_move_counts_as_legal_when_it_is_one_of_the_moves_listed():
    assert swarm.move_is_listed("fold", ["fold", "check"])
    assert swarm.move_is_listed({"action": "fold"}, [{"action": "fold"}, {"action": "call"}])
    assert swarm.move_is_listed(
        {"action": "raise", "amount": 50}, [{"action": "raise", "amount": [40, 200, 1]}]
    )


def test_a_move_the_engine_did_not_offer_is_not_legal():
    assert swarm.move_is_listed({"action": "fold"}, None) is False
    assert swarm.move_is_listed(
        {"action": "raise", "amount": 250}, [{"action": "raise", "amount": [40, 200, 1]}]
    ) is False
    assert swarm.move_is_listed(
        {"action": "raise"}, [{"action": "raise", "amount": [40, 200, 1]}]
    ) is False
    assert swarm.move_is_listed(
        {"action": "raise", "amount": 50, "extra": True},
        [{"action": "raise", "amount": [40, 200, 1]}],
    ) is False


def test_the_player_is_shown_the_moves_as_a_range_not_as_every_number():
    rendered = swarm.format_valid_moves([{"action": "raise", "amount": [40, 200, 1]}])

    assert "Valid moves" in rendered
    assert "[40, 200, 1]" in rendered


def test_the_rules_are_settled_by_the_player_count():
    assert swarm.parse_player_count("... [PLAYER_COUNT: 4]") == 4
    assert swarm.parse_player_count("[PLAYER_COUNT: 9]") is None  # capped at 8
    assert swarm.parse_player_count("no tag at all") is None
    assert swarm.parse_game_name("[GAME_NAME: Skirmish]") == "Skirmish"
    assert swarm.parse_game_name("no name") is None


def test_the_config_silences_automatic_function_calling_and_asks_for_json():
    config = swarm.get_config(system_instruction="Rules", json_mode=True, temperature=0.5)

    assert config.system_instruction == "Rules"
    assert config.response_mime_type == "application/json"
    assert config.temperature == 0.5
    assert config.automatic_function_calling.disable is True


def test_a_client_that_cannot_be_built_is_a_loss_of_service(monkeypatch):
    monkeypatch.setattr(swarm, "_CLIENT", None)
    monkeypatch.setattr(
        swarm.genai, "Client", MagicMock(side_effect=RuntimeError("no key"))
    )

    with pytest.raises(api_errors.BackendUnavailable, match="GEMINI_API_KEY"):
        swarm.get_client()


# ---------------------------------------------------------------------------
# The connection: the front end, driven against the real backend
# ---------------------------------------------------------------------------


def run(state: ui.UIState, text: str) -> list[dict]:
    """One turn with the real backend behind it."""

    return pipeline.run_events(state, text, api=backend_api)


def swarm_ready(gemini: MagicMock, *replies: str) -> None:
    """The rules are settled first time, then these are the one-shot answers.

    The order is the order the run asks for them in: the engine, the first
    player move, the findings, and the review.
    """

    says(gemini, RULES)
    generates(
        gemini,
        f"```python\n{ENGINE_SOURCE}```",
        *replies,
    )


def test_the_whole_run_goes_through_the_real_backend(gemini, state):
    swarm_ready(
        gemini,
        json.dumps({"move": {"action": "pass"}, "explanation": "Nothing beats a pass."}),
        json.dumps(FINDINGS),
        REVIEW,
    )

    run(state, PROMPT)

    # The feed is the one "ui instructions.md" describes, produced by the swarm.
    assert [
        component
        for component in state.components()
        if component.startswith("Status")
    ] == [
        ui.COMPONENT_STATUS_INTERPRETING,
        ui.COMPONENT_STATUS_CODING,
        ui.COMPONENT_STATUS_DEPLOYING,
        ui.COMPONENT_STATUS_PLAYING,
        ui.COMPONENT_STATUS_COLLECTING,
    ]
    assert state.results(ui.COMPONENT_STATUS_INTERPRETING) == ["success"]
    # The code the swarm generated, and the game its agents played, are both
    # there to be shown.
    assert state.code == ENGINE_SOURCE
    assert state.sample[0]["move"] == {"action": "pass"}
    assert state.response == REVIEW
    assert state.title.first(ui.COMPONENT_MULTIWORD).props["pinned"] == "Skirmish"
    assert state.entry(state.awaiting).props["role"] == "next"


def test_the_swarm_drives_the_same_feed_as_the_dummy(gemini, state):
    """The seam the switch sits on, from the front end's side.

    Same prompt, same feed, either side of the switch.  This is the whole of
    what "the front end talks to a bunch of exposed python functions" has to
    mean for the two implementations to be interchangeable.
    """

    swarm_ready(
        gemini,
        json.dumps({"move": {"action": "pass"}, "explanation": "Nothing beats a pass."}),
        json.dumps(FINDINGS),
        REVIEW,
    )
    run(state, PROMPT)

    stand_in = ui.initial_state("other")
    pipeline.run_events(stand_in, PROMPT, api=dummy_api)

    assert state.components() == stand_in.components()


def test_a_question_from_the_swarm_loops_back_into_interpreting(gemini, state):
    says(
        gemini,
        "How many players are there, and what is a legal turn?",
        RULES,
    )
    generates(
        gemini,
        f"```python\n{ENGINE_SOURCE}```",
        json.dumps({"move": {"action": "pass"}, "explanation": "Nothing beats a pass."}),
        json.dumps(FINDINGS),
        REVIEW,
    )

    run(state, "something fun, you decide everything")

    # Interpreting failed because it needed clarification, and the question is
    # waiting for an answer in the feed.
    assert state.results(ui.COMPONENT_STATUS_INTERPRETING) == ["failure"]
    question = state.entries[-1]
    assert question.component == ui.COMPONENT_STATUS_QUESTION
    assert "How many players" in question.props["text"]
    assert state.entry(state.awaiting).props["role"] == "question"
    assert state.code is None

    run(state, "Two players, and a turn is passing.")

    # The answer went into the same conversation, so the run carries on.
    assert state.results(ui.COMPONENT_STATUS_INTERPRETING) == ["failure", "success"]
    assert state.status_result(ui.STATUS_COLLECTING) == "success"
    assert state.response == REVIEW


def test_the_swarm_keeps_asking_until_the_rules_hold_up(gemini, state):
    says(gemini, "How many players?", "And how does a turn end?", "How do you win?", RULES)
    generates(
        gemini,
        f"```python\n{ENGINE_SOURCE}```",
        json.dumps({"move": {"action": "pass"}, "explanation": "Nothing beats a pass."}),
        json.dumps(FINDINGS),
        REVIEW,
    )

    run(state, "a game where you pass until you win")
    for answer in ("Two players.", "A turn is passing.", "Whoever passed first wins."):
        run(state, answer)

    assert state.results(ui.COMPONENT_STATUS_INTERPRETING) == [
        "failure",
        "failure",
        "failure",
        "success",
    ]
    assert state.response == REVIEW


def test_a_lost_service_shows_a_failure_and_offers_the_run_again(gemini, state):
    says(gemini, RULES)
    generates(gemini, RuntimeError("the swarm is down"))

    run(state, PROMPT)

    assert state.status_result(ui.STATUS_CODING) == "failure"
    assert state.failures
    assert state.response is None
    # The user is not stuck: the "What's next?" editor is waiting again.
    assert state.entry(state.awaiting).props["role"] == "next"


def test_the_front_end_runs_against_the_dummy_when_the_switch_is_on(gemini, state):
    """The same flow, the other side of the switch, with nothing mocked out."""

    pipeline.run_events(state, "A two player game of tic tac toe. Three in a row wins.")

    assert state.response
    assert state.title.first(ui.COMPONENT_MULTIWORD).props["pinned"] == "Tic-Tac-Toe"
    # The swarm was never asked anything, because it was not the one answering.
    assert gemini.chats.create.call_count == 0
    assert gemini.models.generate_content.call_count == 0


def test_the_page_runs_the_real_swarm_when_the_switch_is_off(
    monkeypatch, gemini, submit, toggle
):
    """The whole way through, over HTTP, with the swarm answering."""

    monkeypatch.setattr(app, "USE_DUMMY_API", False)
    swarm_ready(
        gemini,
        json.dumps({"move": {"action": "pass"}, "explanation": "Nothing beats a pass."}),
        json.dumps(FINDINGS),
        REVIEW,
    )
    toggle("code", True)

    feed = submit(PROMPT)

    assert feed.components[:3] == ["Title", "Multiword", "PromptEditor"]
    # The generated engine and the review are on the page, streamed by the swarm.
    assert "def initial_game_state" in feed.html_of("LongBlockCode")
    assert REVIEW in feed.text
    assert "What's next?" in feed.text
    assert "Skirmish" in feed.html_of("Title")


def test_a_normal_run_with_no_swarm_shows_a_failure_not_a_traceback(
    monkeypatch, submit
):
    """The switch off and no key to spend: the page still works."""

    monkeypatch.setattr(app, "USE_DUMMY_API", False)
    monkeypatch.setattr(swarm, "_CLIENT", None)
    monkeypatch.setattr(
        swarm.genai, "Client", MagicMock(side_effect=RuntimeError("no key"))
    )

    feed = submit(PROMPT)

    assert feed.count("StatusInterpreting") == 1
    assert 'data-result="failure"' in feed.html_of("StatusInterpreting")
    # Nothing downstream of the failure happened, and the user can try again.
    assert feed.count("StatusCoding") == 0
    assert "What's next?" in feed.text
